FROM node:24.19.0-alpine

ENV NODE_ENV=production
WORKDIR /app

# package-lock.json is intentionally generated by `npm install` when upgrading
# the legacy repository. Once committed, this can be changed to `npm ci`.
COPY package.json ./
RUN npm install --omit=dev --no-audit --no-fund \
    && npm cache clean --force

COPY --chown=node:node src ./src

USER node
EXPOSE 3000

HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=6 \
  CMD node -e "fetch('http://127.0.0.1:3000/ready').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"

CMD ["node", "src/server.mjs"]
